#+title: Something

* Draft
Within a page, within a book, in the corner of a dusty shelf, in an even dustier
corner of the least-frequented and most-disused portion of the University
College London Library, is the word "gloomp." The word is by itself, no more spaced
out from its neighbours than any other word in the book, yet clearly, and
emphatically, by itself. The words to its right and left, those above and below,
are inconsequential; it reflects none of them; it does not join in the music of
meaning, as any self-respecting word would. Skipping along to the steady
beat of the story, losing oneself in the orchestral composition of images struck
up by the phrases, the paragraphs, the page-long stretches of language which
pulse with a promise of revelation, in the same way each dark wave in the
sea promises to break, albeit briefly, into a brilliant white froth, embedded in
this music, like a hiccup, or a loud clunk, is the word: gloomp.

It may be a printing error; the book is old. It may be an innocent and
harmless mistake.

It may be that the typesetters thought it funny to hide this nonsensical word
within a book, a sort of signature, a way for them to say, "we were here,"
giving the reader a sense of there being more than two people in the room of
their reading, that is, someone eavesdropping on her close and private
intimations with the writer.

It may be that the senior editor, on the verge of death-sleep, whose fields of
total oblivion can only be roamed by those most hard-working of spirits, felt
the thrum of something primal, something deeper than himself; his neocortex
slowly drifting into its regular theta rhythms, the limbic whispers began to
rise, once just barely audible, now chanting with the
impelling force of an orgiastic ritual, recruiting spine and limbs to
communicate the dictates of the hidden universe, indescribable, fleeing from
reason, crystallising only in the obscure and infinitely layered truth
that is the word "gloomp"--which he etched in a scrawl as his drool puddled
delicately on the hardwood desk.

Or perhaps the writer themselves made the mistake.

Or perhaps no mistake at all. It may be that this word, "gloomp", holds a
crucial position within the entire composition. It may be that whatever thing it
seems /not/ to say, is exactly what it /does/, and the very act of not saying it is
a way for the writer to say something about the story itself; that this dark
atom of absence in a world of meaning is the very linchpin that gives
the light its radiance, that gives 'meaning' any meaning at all ---
or so would one academic write, going on to earn some measure of respect, at
least among the seven or eight other individuals that made the entire body of
his specific substratum of a niche field; enough respect, that is, to earn him a
pint of beer, and a publication.

In any case, there it is: "gloomp."
